name    'guilhermef-wight'
version '0.0.7'
author 'guilhermef'
license 'MIT'
summary 'Module for https://github.com/heynemann/wight'
description 'Module for https://github.com/heynemann/wight'
project_page 'https://github.com/guilhermef/wight-puppet'

dependency 'guilhermef/supervisor'
